# Generated by Django 3.1.5 on 2021-01-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='category',
            field=models.CharField(default='action', max_length=200),
        ),
    ]
