# Generated by Django 3.1.5 on 2021-01-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='imagea/None/Noimg.jpg', upload_to='Images/'),
        ),
    ]
